### ISSUE TITLE
Submit theme to various Hugo theme directories

### ISSUE THREAD

**Issue by cjyabraham** [cncf/dot-org-hugo-theme#12]
**Hugo Themes Directory**
1) Read theme submission guidelines - https://github.com/gohugoio/hugoThemesSiteBuilder/blob/main/README.md#hugo-themes
2) Make pull request in https://github.com/gohugoio/hugoThemesSiteBuilder

**Jamstack Themes**
Follow https://jamstackthemes.dev/ssg/hugo/

**StaticHunt**
Follow https://github.com/statichunt/statichunt#submission-guides 

**Hugo Themes Free**
No submission process at https://hugothemesfree.com

**Comment by thetwopct** [comment]
✅ Submitted to [Hugo Themes](https://github.com/gohugoio/hugoThemesSiteBuilder/pull/354)
✅ Submitted to [Jamstack Themes](https://github.com/stackbit/jamstackthemes/pull/430)
✅ Submitted to [StaticHunt](https://github.com/statichunt/statichunt/pull/26)

I couldn't find any more, LMK if any others come to mind?

**Comment by cjyabraham** [comment]
Looks like [it's up on Hugo Themes already](https://themes.gohugo.io/themes/dot-org-hugo-theme/)!

**Comment by thetwopct** [comment]
And now on https://jamstackthemes.dev 

Ideally I would like to update the thumbnail to something a bit better looking, but not a priority now

I'll close this off for now, if any more listings come up lets re-open

**Comment by thetwopct** [comment]
Listed on StaticHunt - https://statichunt.com/themes/hugo-dot-org
