### ISSUE TITLE
Feature: collapsible footer on mobile? 

### ISSUE THREAD

**Issue by marvin-hansen** [cncf/dot-org-hugo-theme#14]
Hi,

I'm seeing increasingly on well made mobile sites that the entire footer is collapsible which nicely declutters the site.

Examples (On mobile only)
https://ressencewatches.com/
https://deepdreamgenerator.com/about

 I am wondering, if you are open to add a collapsible mobile footer to this theme? 

If possible, it would be great to have a config flag to turn in on/off because preferences may differ.

**Comment by thetwopct** [comment]
Yep, should be possible. Could copy the same sort of code used in the mobile menu.

I'm not a fan of it generally (I don't like the UI pattern of requiring a user to click just to see information, and having the links on page makes them accessible, not hidden behind JS). It's definitely useful when the site/menu has a lot of links, like news sites tend to have - I don't mind how [NY Times](https://www.nytimes.com) have approached it, looks quite elegant. [The Guardian](https://www.theguardian.com/uk) (arguably the most cutting-edge media site out there, certainly one [heavily focused](https://uxdesign.cc/designing-a-new-mobile-experience-for-the-guardian-bea90f38e59e) on user friendly design patterns) just leave the links, but there aren't as many as NYT have hidden.

**Comment by marvin-hansen** [comment]
@thetwopct 

Thank you James, 

you're touching a lot of good points. 

Basically, when you have to declutter the footer, it was bad design in the first place. That reasoning makes a lot of sense. Maybe the collapsible footer really is just a fix for something that shouldn't be broken to begin with. 

What I can say though, based on your input and examples, I have minimized my site footer and it's way better now so I tend to agree with your reasoning to fix the design first.

I leave the decision to ignore or try the idea to you as don't have the ultimate answer.

**Comment by cjyabraham** [comment]
Closing this as I don't think we need it, at least in this parent theme. It may make sense for a particular website aesthetic but could then be implemented in the child theme.
