### ISSUE TITLE
Secondary button hover style should not look like primary button

### ISSUE THREAD

**Issue by cjyabraham** [cncf/dot-org-hugo-theme#16]
I think having the secondary button hover color be identical to the primary color button is problematic, especially when you have both buttons next to each other. You end up getting two identical buttons showing when you hover over the secondary button. In this screenshot I am currently hovering over the middle button which turned from bright green to this color (try on [demo page here](https://main--dot-org-hugo-theme-demo.netlify.app/demo-page/)):

![Screenshot 2023-09-17 at 11 17 59 AM](https://github.com/cncf/dot-org-hugo-theme/assets/463160/db8ef39e-3491-430a-9bb4-722711884b9b)

I think a good fix is to make the secondary button hover color a slightly darker shade of its regular color, maybe try #4d8307 ?

**Comment by thetwopct** [comment]
Updated
