### ISSUE TITLE
Mobile menu right margin inconsistent

### ISSUE THREAD

**Issue by cjyabraham** [cncf/dot-org-hugo-theme#17]
Could we make this right margin consistent so that these lines go to the same margin as the button and language selector below?

![Screenshot 2023-09-17 at 12 17 09 PM](https://github.com/cncf/dot-org-hugo-theme/assets/463160/a1f075cb-67b4-4fbc-80bf-a399bd00d3b2)

**Comment by thetwopct** [comment]
Fixed
