### ISSUE TITLE
exampleSite: site.Language.Params is deprecated, use site.Params directly

### ISSUE THREAD

**Issue by doolio** [cncf/dot-org-hugo-theme#20]
[Per the Hugo docs](https://gohugo.io/content-management/multilingual/#changes-in-hugo-01120).

Considering this should the following be moved to params.yaml?

https://github.com/cncf/dot-org-hugo-theme/blob/a614d0d4fd67ae2365c2d80f0ce93ec99bcab3ef/exampleSite/config/_default/languages.yaml#L4-L21

**Comment by thetwopct** [comment]
Thanks, we've updated
