### ISSUE TITLE
Some node modules are deprecated

### ISSUE THREAD

**Issue by doolio** [cncf/dot-org-hugo-theme#22]
![image](https://github.com/cncf/dot-org-hugo-theme/assets/13859009/f99743c7-2b93-454c-861d-e00e6587731f)

**Comment by doolio** [comment]
Looking again all the deprecated packages are from the same author. They provide some advice [here](https://github.com/lydell/urix#deprecated), [here](https://github.com/lydell/source-map-url#deprecated), [here](https://github.com/lydell/source-map-resolve#deprecated) and [here](https://github.com/lydell/resolve-url#deprecated) for each deprecated module respectively.

**Comment by thetwopct** [comment]
Related https://github.com/netlify/cli/issues/5724 

> The deprecations are minor and do not affect security or usability, and can IMO only be an attack vector if you're providing netlify-cli as a service. 

Once fixed on Netlify side I will update

**Comment by thetwopct** [comment]
Updated and released in https://github.com/cncf/dot-org-hugo-theme/releases/tag/v0.1.5
