### ISSUE TITLE
Menu names do not align in footer

### ISSUE THREAD

**Issue by doolio** [cncf/dot-org-hugo-theme#25]
Taken from the TODO Group site. The blog menu name does not have any submenus listed under it to align with the other menu items. The blog page however does have blog posts. Perhaps link to 3-4 of the most recent blog posts to fix the alignment? 

![image](https://github.com/cncf/dot-org-hugo-theme/assets/13859009/6381b500-bb82-4a9b-b44e-fa365c7ab344)

On the other real life example site Deep Causality it seems any menus with no submenus are grouped together on the right of the menu items with submenus.

![image](https://github.com/cncf/dot-org-hugo-theme/assets/13859009/66bd4df1-bdeb-478b-b856-558c73b81396)

**Comment by thetwopct** [comment]
I've been thinking about this, and I can't really see a better way to organise these links. We need to allow for mega menu headers and children, and likewise we need to allow for top level links. Top level links do not have a header, so aligning them at the top of this section looks strange to me as the styling of the text is different. Instead they are aligned with other children. I think it works in both the screenshots shown. Until I see a better option, I am going to leave this as is. 

Suggestions/PRs welcome.
