### ISSUE TITLE
Unable to override favicon

### ISSUE THREAD

**Issue by doolio** [cncf/dot-org-hugo-theme#27]
I have placed the following files of my own favicon in `/static/` but they do not override the themes favicon.

```
favicon-16x16.png
favicon-32x32.png
favicon.ico
```

**Comment by thetwopct** [comment]
Are you able to share your sites URL?

**Comment by doolio** [comment]
It's not yet published but let me configure a preview-deploy.

**Comment by doolio** [comment]
It seems it is necessary to add a `favicon.svg` to the list of files above to override the theme favicon. Therefore closing.

**Comment by thetwopct** [comment]
Thanks for updating!
