### ISSUE TITLE
Unused shortcodes should use INFO rather than WARN debug level

### ISSUE THREAD

**Issue by doolio** [cncf/dot-org-hugo-theme#28]
If a shortcode is unused then it shouldn't be logged as a warning. An example:

![image](https://github.com/cncf/dot-org-hugo-theme/assets/13859009/47bd4d8e-c441-4fae-9822-a2d074fef3d9)

**Comment by thetwopct** [comment]
Feel free to use your own hugo serve or npm script command that suits your liking
