### ISSUE TITLE
README describes non-existing frontmatter

### ISSUE THREAD

**Issue by doolio** [cncf/dot-org-hugo-theme#30]
Should the following line:
https://github.com/cncf/dot-org-hugo-theme/blob/a614d0d4fd67ae2365c2d80f0ce93ec99bcab3ef/README.md?plain=1#L105

be `showHeader: false` considering this [commit](https://github.com/cncf/dot-org-hugo-theme/commit/b43b1159834fcef4e345795205e882475dc47b52). I could find no other reference to `hideHeader`.

**Comment by thetwopct** [comment]
Nice catch, I need to update the readme as I renamed it at last minute

**Comment by thetwopct** [comment]
Updated
