### ISSUE TITLE
exampleSite: .prettierrc and hugo_stats.json out of place

### ISSUE THREAD

**Issue by doolio** [cncf/dot-org-hugo-theme#31]
I presume `prettier` is used for development so shouldn't `.prettierrc` be in the root of the repository?

`hugo_stats.json` seems like a good candidate for inclusion in the gitignore, no?

**Comment by thetwopct** [comment]
Noted on hugo_stats.json

The prettierrc and the Hugo plugin never worked for me, so have got rid of it - an easy way to solve a problem :)

**Comment by thetwopct** [comment]
Released in v0.1.3
