### ISSUE TITLE
[Feature Request] Add Search Option

### ISSUE THREAD

**Issue by sunny0826** [cncf/dot-org-hugo-theme#35]
I was recently doing some work on the TODO Group website and realized that the site does not have a search function, which is not conducive to retrieving information. Would it be possible to add a search option to this hugo theme, there are some recommendations in the [hugo documentation](https://gohugo.io/tools/search/)?

### recommended

**Open source**
- [pagefind](https://pagefind.app/docs/ui-usage/)
- [hugo-lyra](https://github.com/paolomainardi/hugo-lyra)

**Commercial** 
- [algolia](https://www.algolia.com/)

**Comment by thetwopct** [comment]
Yes good feedback, I'm not sure how the original design missed adding a search. We will look to add retrospectively.

**Comment by cjyabraham** [comment]
I've done some experimenting recently with Pagefind on the Kubernetes site and am impressed with it. Here's [the PR for Kubernetes](https://github.com/kubernetes/website/pull/44530).

**Comment by cjyabraham** [comment]
Here's [the PR](https://github.com/cncf/dot-org-hugo-theme/pull/37) for this theme. Please test it out the preview instance: https://deploy-preview-37--dot-org-hugo-theme-demo-jh.netlify.app/

**Comment by cjyabraham** [comment]
This is done.
