### ISSUE TITLE
Provide a sticky header option for the theme

### ISSUE THREAD

**Issue by thetwopct** [cncf/dot-org-hugo-theme#4]
Similar to what is used on cncf.io see if its easy to build an option so that sticky header can be turned on and off via config

**Comment by doolio** [comment]
> Similar to what is used on cncf.io

The header doesn't appear to be sticky on cncf.io. It is though on the [Chips Alliance](https://www.chipsalliance.org/) site which uses the [Sendit Hugo theme](https://github.com/chipsalliance/chips-alliance-website).

**Comment by cjyabraham** [comment]
Are you on [www.cncf.io](https://www.cncf.io/)? It should be sticky there. If not, can you provide [your browser info](https://debug.thetwopercent.co.uk/)?

**Comment by doolio** [comment]
> Are you on [www.cncf.io](https://www.cncf.io/)?

Yes.

> It should be sticky there. If not, can you provide [your browser info](https://debug.thetwopercent.co.uk/)?

That site reported my browser as `v102.0` when in fact it is `v102.15.lesr`.
```
Device Debug
    Screen Width: 1366
    Screen Height: 768
    Viewport Width: 1364
    Viewport Height: 602
    Browser: Mozilla Firefox 102.15.lesr
    Operating System: Linux
    Raw Browser Info: Mozilla/5.0 (X11; Linux x86_64; rv:102.0) Gecko/20100101 Firefox/102.0
```

**Comment by cjyabraham** [comment]
On cncf.io, since your viewport height is less than 615px, the header will not be sticky for you to save you some limited vertical real estate. If you expand your viewport taller than 615px then you'll see that the header is sticky.

**Comment by doolio** [comment]
I see, thanks for the explanation. I can see it is indeed sticky when I enable full screen mode. I would have assumed it would scale appropriately depending on the device. Do I change [this line](https://github.com/cncf/dot-org-hugo-theme/blob/a614d0d4fd67ae2365c2d80f0ce93ec99bcab3ef/layouts/partials/head.html#L6) to expand my viewport? I note it only specifies a width and not a height.

**Comment by cjyabraham** [comment]
Your viewport is the viewable area inside your browser. To expand your viewport try expanding your browser or, if necessary, use a larger monitor.

**Comment by doolio** [comment]
Ah I see thank you. At the moment the most I can do is enter full screen mode and as already stated I can then see the sticky header. Thanks again.
