### ISSUE TITLE
FR: Menu children should collapse on mobile when selecting between menus

### ISSUE THREAD

**Issue by doolio** [cncf/dot-org-hugo-theme#42]
On mobile, if you select one menu with children you see the menu, its children below it and then the other menus below that. However, if you then select another top-level/parent menu the children of the first top-level.parent menu are still visible. I would expect the children to collapse when selecting between top-level/parent menus. ideally, if the hamburger menus on mobile could behave like the FAQ page when selecting between the FAQs.

I hope what I describe is clear.

**Comment by thetwopct** [comment]
Yes, it's clear, thanks. I find the FAQ closing/opening a little jerky, and with the length that some sub-menus can get too I don't think it would offer a great experience. 

Looking around the web, most sites I inspect use the same method of keeping the sub-menu open. I only managed to find one site (Oracle) that closes the sub-menu  when opening another, and the way that works with the menus jumping up and down is not something I personally like as an experience.

If this get some likes on your post we can reconsider implementation or try to make it as an option, but for now will be closing as Not Planned.

**Comment by doolio** [comment]
OK, thank you for considering it in any case.
