### ISSUE TITLE
Make Twitter cards optional via config

### ISSUE THREAD

**Issue by ahoog42** [cncf/dot-org-hugo-theme#44]
I've stop supporting Twitter/X but the Twitter card metadata is hardcoded into the theme ([website](https://www.board-cybersecurity.com)). Would it be possible to make this optional via the config?

**Comment by thetwopct** [comment]
Not an option, but the twitter card has now been added a partial. So if users want to remove the Twitter cards specifically, they can add an empty file here `layouts/partials/head/twitter-cards.html` and the content will then not be loaded.
