### ISSUE TITLE
Can't nest img shortcodes in columns or cards

### ISSUE THREAD

**Issue by cjyabraham** [cncf/dot-org-hugo-theme#51]
For some reason I can't nest an image shortcode `{{< img src="/img/blog/image-name.png" >}}` inside a column or card shortcode. It just renders the raw html directly in the browser. The spacer shortcode, however, can be nested successfully.

**Comment by thetwopct** [comment]
Does the [info here resolve it](https://github.com/cncf/dot-org-hugo-theme?tab=readme-ov-file#custom-shortcodes)? It's likely some kind of escaping that happens inside shortcodes.

**Comment by cjyabraham** [comment]
No. I have that config snippet in place and it's still dumping raw html to the browser.
