### ISSUE TITLE
Is there an option to place a custom main page instead of dynamic list of pages?

### ISSUE THREAD

**Issue by marvin-hansen** [cncf/dot-org-hugo-theme#6]
Hi,

I just adopted the theme and so far its been great. Things are working out of the box, customization is easy, site speed is phenomenal, and I got a lot done in little time. 

However, there is one issue I cannot get my head around: The main page "/" gets cluttered with a dynamic list of all other pages.

See the site preview:

https://beta-7j9.pages.dev/

Is there an option to switch this off so I can just write a custom welcome page instead?

I read through the documentation, but wasn't able to find anything. 

Please let me know.

Thank you

**Comment by thetwopct** [comment]
Hey Marvin

Thanks for using dot-org and great question!

We didn't add an index/home page as didn't want to be too opinionated as to how users may use the theme, and how to add one depends on how you're using Hugo.

We have a site [already using this theme](https://github.com/todogroup/todogroup.org/tree/redesign) and for that site we added the following:

`/layout/index.html`

The contents of that should look something like this:

```
{{ define "main" }}
  <h1>Welcome</h1>
  <p>Lorem ipsum dolor sit amet consectetuer adipiscing elit aenean commodo</p>
  <img src="https://via.placeholder.com/250x200/d9d9d9/000000" alt="Some image">
{{ end }}

```
We then added another file to pass front matter to the html file:

`/content/en/_index.md`

which our content has content something like the following:

```
---
showHeader: false
---

# This file is used to pass params to the index/home.
```

This file could have more in it depending on your Hugo plugins etc. 

You would then to replicate the _index.md in to other content/ language directories that you use.

Once that's in place the index.html can be edited as you want. To make it international with translations, you could use /i18n/ data files and variable names. The site [already using this theme](https://github.com/todogroup/todogroup.org/tree/redesign) does this too. 

Note: Very often you need to restart the Hugo build process for the new layout to resolve and display properly. 

If there is enough demand to add a home page to the theme then I can add it.

**Comment by marvin-hansen** [comment]
@thetwopct Thank you,

I tinkered around with the example code and after having copied over the SCSS & i18 files, things worked out just fine.

https://beta-7j9.pages.dev/

I think I can take if from here and do my customization as the overall idea is about right. 
Restarting Hugo a few more times and things should be alright :-) 

I have to be honest, this theme is actually a lot more useful, carefully designed, and thought through that it appears on the surface. Impressive work! 👍 

That said, it would be great if you would copy your answer and put it somewhere in the documentation to give people with less background in  Hugo themes a starting point.

**Comment by marvin-hansen** [comment]
James, 

Just a quick follow up question:

The .box-grid on my site is rendered vertically instead of horizontally although I literally copied over the index.html and custom layouts of the sample code. I've read through the box SCSS & docs and it should arrange from left to right, but somehow it does so from top to bottom.

https://beta-7j9.pages.dev/

Are there any other SCSS files or anything else to get a vertical alignment of the grid box?

https://github.com/marvin-hansen/sites/blob/main/web/layouts/index.html

**Comment by thetwopct** [comment]
How are you loading the styles for this that are in home.css? The home CSS is only used on the home page so we specifically load it there. In the TODO use of this theme the custom stylesheet is loaded in the custom-head.html - see:

https://github.com/todogroup/todogroup.org/blob/redesign/layouts/partials/head/custom-head.html

**Comment by marvin-hansen** [comment]
This custom head actually throws me an error:

```
ERROR Rebuild failed: process: "/Users/marvin/CLionProjects/sites/web/layouts/partials/head/custom-head.html:11:1":
 parse failed undefined variable "$style"
Total in 6 ms
```

Specifically, the last three lines of the custom head causing the problem:

```
{{ if (eq .Kind "home") }}
<link rel="stylesheet" href="{{ $style.RelPermalink }}" integrity="{{ $style.Data.Integrity }}" media="all">
{{ end }}
```

I don't know what the error causes

**Comment by marvin-hansen** [comment]
Here is the full stacktrace from Hugo:

```
 Rebuild failed: render: failed to render pages: render of "page" failed: "../web/themes/dot-org-hugo-theme/layouts/_default/baseof.html:3:8": 
execute of template failed at <partial "head.html" .>: error calling partial: ".../web/themes/dot-org-hugo-theme/layouts/partials/head.html:18:8": 
execute of template failed at <partial "head/custom-head.html" .>: ".../web/layouts/partials/head/custom-head.html:9:46": 
execute of template failed at <resources.ToCSS>: 
error calling ToCSS: no Resource provided in transformation
Total in 16 ms
```

**Comment by marvin-hansen** [comment]
@thetwopct This is solved. There was an incorrect path in my custom-head file that causes $source to be null.

I'm closing this issue as my main page is now working fine.

Thank you for the hint at the custom head.html.
