### ISSUE TITLE
ExampleSite pages not working?

### ISSUE THREAD

**Issue by shivahnshankar** [cncf/dot-org-hugo-theme#62]
Hi
I followed the instructions to run a site locally using the exampleSite content. The homepage works but none of the other pages work. I get 404 error even though the about and demo content md files are present.
No customisation. Any pointers on how to troubleshoot? Thanks

**Comment by shivahnshankar** [comment]
Btw i see that the demo site has the same issue.

**Comment by thetwopct** [comment]
@shivahnshankar Thanks for picking this up and alerting us! We missed this issue. We have created a fix and released a new version of the theme. Thank you.
