### ISSUE TITLE
Mobile footer: add some space between copyright and subsequent links

### ISSUE THREAD

**Issue by cjyabraham** [cncf/dot-org-hugo-theme#7]
![Screenshot 2023-09-05 at 11 39 44 AM](https://github.com/cncf/dot-org-hugo-theme/assets/463160/468f0f74-a4ff-435b-a2da-1c7eec4d810d)

**Comment by thetwopct** [comment]
Is this because of a flagged tap target size issue? The screenshot doesn't look like mobile.

**Comment by cjyabraham** [comment]
I just thought it would make sense to keep those links separate from the copyright notice, as they are on desktop, but, yes, also good to meet the target tap size requirements. Here's a better mobile screenshot from the todo theme:
<img src="https://github.com/cncf/dot-org-hugo-theme/assets/463160/1070ed44-40ba-47cd-b1f8-dcc53179c782" width=400px>

**Comment by thetwopct** [comment]
Added margin on mobile
